"""M4 bounded receivers, folds and per-receiver construction (contract §5.1.1–§5.1.5, §5.1.11; spec §9 / §10 M4).

The byte-identity gate of contract §5.1.2 / §5.1.8 / §5.1.11: with the new features switched off, the SVG of
every v2 conformance scene equals the v2 writer's output (``tests/golden/v2_svg_sha256.json``, generated by the
v2 code before M4) and the geometry JSON with the M4 keys stripped (``tools/regen_conformance.py
--strip-new-keys``) equals the committed v2 expected file.
"""

from __future__ import annotations

import hashlib
import json
import pathlib

import pytest

import castplane

ROOT = pathlib.Path(__file__).resolve().parents[1]
CASES = ROOT / "tests" / "conformance" / "cases"
GOLDEN = json.loads((ROOT / "tests" / "golden" / "v2_svg_sha256.json").read_text(encoding="utf-8"))


def v2_case_names() -> list[str]:
    return sorted(GOLDEN["sha256"])


def test_golden_hashes_cover_the_34_v2_cases():
    assert len(GOLDEN["sha256"]) == 34
    assert set(GOLDEN["sha256"]) <= {p.stem for p in CASES.glob("*.json")}


def _regen():
    import importlib.util
    spec = importlib.util.spec_from_file_location("regen_conformance_m4", ROOT / "tools" / "regen_conformance.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


@pytest.mark.parametrize("name", v2_case_names())
def test_switch_off_svg_and_stripped_json_are_byte_identical_to_v2(name):
    from castplane.output.geometry_json import dumps
    scene = castplane.load_scene(CASES / f"{name}.json")
    result = castplane.render(scene)
    recorded_build = GOLDEN["build"].endswith(f"numpy {__import__('numpy').__version__}")
    if recorded_build:
        assert hashlib.sha256(result["svg"].encode("utf-8")).hexdigest() == GOLDEN["sha256"][name]
    full_text = dumps(result["geometry"]) + "\n"
    doc = json.loads(full_text)
    assert doc["hidden_lines"] is False and len(doc["receivers"]) == 1
    stripped, problems = _regen().strip_new_keys(doc)
    assert problems == []
    expected_text = (ROOT / "tests" / "conformance" / "expected" / f"{name}.json").read_text(encoding="utf-8")
    if '"hidden_lines":' in expected_text:
        # after the v4 key-additive regeneration (contract §5.0.8) the expected file carries the M4 keys: the
        # render equals it byte for byte, and the v2 document is the expected file with the M4 keys stripped
        if recorded_build:
            assert full_text == expected_text
        expected_v2, problems = _regen().strip_new_keys(json.loads(expected_text))
        assert problems == []
        expected_text = dumps(expected_v2) + "\n"
    if recorded_build:
        assert dumps(stripped) + "\n" == expected_text
    else:   # another libm: the spec §7.5 tolerances (contract §4) and the SVG structure of the v2 document
        from tests.test_conformance import compare_documents
        assert compare_documents(json.loads(expected_text), stripped, name) == []
        from castplane.output.svg import write_svg
        v2_svg = write_svg(json.loads(expected_text), layers=scene["output"]["layers"])
        assert svg_structure(result["svg"]) == svg_structure(v2_svg)


def svg_structure(svg: str) -> list:
    """The element sequence of an SVG with its ids and every attribute except the coordinates (numbers that
    may differ by an ulp on another libm): tags, ids, styles and group nesting."""
    import re
    return [re.sub(r"-?\d+(\.\d+)?(e-?\d+)?", "#", m) for m in re.findall(r"</?[a-z]+[^>]*>", svg)]


def test_svg_structure_ignores_numbers_only():
    a = '<g id="x.v1"><path d="M1.25 2 L3 4Z" fill-opacity="0.3"/></g>'
    assert svg_structure(a) == svg_structure(a.replace("1.25", "1.2500000001").replace("0.3", "0.3"))
    assert svg_structure(a) != svg_structure(a.replace('id="x.v1"', 'id="y.v1"'))
    assert svg_structure(a) != svg_structure(a.replace("<path", "<polyline"))


def test_strip_new_keys_mode_of_the_regen_tool():
    import subprocess
    import sys
    r = subprocess.run([sys.executable, str(ROOT / "tools" / "regen_conformance.py"), "--reason", "check",
                        "--strip-new-keys", "--case", "example_basic", "--case", "example_curved_demo"],
                       capture_output=True, text=True, cwd=ROOT)
    assert r.returncode == 0, r.stderr
    assert "2 of 2 case(s) with zero mismatches" in r.stdout
    # an M4 case's expected file already carries the M4 keys: compared unstripped (step 10), so the mode can run
    # on the whole set before the v4 regeneration
    r = subprocess.run([sys.executable, str(ROOT / "tools" / "regen_conformance.py"), "--reason", "check",
                        "--strip-new-keys", "--case", "wall_and_ground_hidden", "--case", "example_basic"],
                       capture_output=True, text=True, cwd=ROOT)
    assert r.returncode == 0, r.stderr
    assert "2 of 2 case(s) with zero mismatches" in r.stdout
    r = subprocess.run([sys.executable, str(ROOT / "tools" / "regen_conformance.py"), "--reason", "check",
                        "--strip-new-keys", "--rules-only"], capture_output=True, text=True, cwd=ROOT)
    assert r.returncode == 2


def test_strip_new_keys_reports_non_switch_off_values():
    regen = _regen()
    doc = {"hidden_lines": True, "receivers": [], "construction": {"per_receiver": {"wall": {}}},
           "edges": [{"runs": [{"s": [0, 1]}], "visibility": "partial"}], "outlines": [], "form_shadow": [],
           "shadows": [{"polygon_edges": [], "conics": [{"visibility": "visible", "runs": []}]}]}
    _doc, problems = regen.strip_new_keys(doc)
    joined = "\n".join(problems)
    for needle in ("hidden_lines", "receivers", "per_receiver", "edges[0].runs", "edges[0].visibility",
                   "shadows[0].conics[0]: missing hidden_polylines"):
        assert needle in joined, (needle, problems)


# --------------------------------------------------------------------------- shadow.py unit tests (§5.1.2, §5.1.3.3)
import math

import numpy as np

from castplane.shadow import bounds_functionals, clip_polygon_bounds, plate_loop, receiver_frame

#: The wall plate of ``wall_and_ground``: the plane y = 6 with normal (0, -1, 0); its frame is (x, z).
WALL_N = np.array([0.0, -1.0, 0.0])
WALL_PI = np.array([0.0, -1.0, 0.0, 6.0])
WALL_BOUNDS = np.array([[-3.0, 6.0, 0.0], [3.0, 6.0, 0.0], [3.0, 6.0, 2.5], [-3.0, 6.0, 2.5]])


def wall_point(u, v, w=1.0):
    """Homogeneous point of the wall plane with frame coordinates ``(u, v) = (x, z)``, scaled by ``w > 0``."""
    return np.array([u * w, 6.0 * w, v * w, w])


def wall_dir(du, dv):
    n = math.hypot(du, dv)
    return np.array([du / n, 0.0, dv / n, 0.0])


def frame_area(V) -> float:
    e1, e2 = receiver_frame(WALL_N)
    X = V[:, :3] / V[:, 3:4]
    uv = np.stack([X @ e1, X @ e2], axis=1)
    x, y = uv[:, 0], uv[:, 1]
    return 0.5 * float(np.sum(x * np.roll(y, -1) - np.roll(x, -1) * y))


def clip_wall(poly):
    poly = np.array(poly, dtype=np.float64)
    psi = bounds_functionals(WALL_BOUNDS, WALL_N)
    return clip_polygon_bounds(poly, list(range(len(poly))), psi, WALL_BOUNDS, 1e-9)


def test_receiver_frame():
    e1, e2 = receiver_frame([0.0, 0.0, 1.0])
    assert e1.tolist() == [1.0, 0.0, 0.0] and e2.tolist() == [0.0, 1.0, 0.0]       # the ground: (x, y)
    e1, e2 = receiver_frame(WALL_N)
    assert np.allclose(e1, [1, 0, 0]) and np.allclose(e2, [0, 0, 1])
    for n in ([0.0, 0.0, -1.0], [0.0, -0.6, 0.8], [0.48, 0.6, 0.64], [1.0, 0.0, 0.0]):
        n = np.array(n)
        e1, e2 = receiver_frame(n)
        assert np.allclose(np.cross(e1, e2), n, atol=1e-15)
        assert abs(float(e1 @ e2)) <= 1e-15 and abs(np.linalg.norm(e1) - 1) <= 1e-15


def test_bounds_functionals_are_unit_inward_normals():
    psi = bounds_functionals(WALL_BOUNDS, WALL_N)
    assert np.allclose(psi, [[0, 0, 1, 0], [-1, 0, 0, 3], [0, 0, -1, 2.5], [1, 0, 0, 3]])
    # signed distance times w for a finite point, m_k . d for a direction
    X = wall_point(1.0, 1.0, w=7.0)
    assert np.allclose(psi @ X, 7.0 * np.array([1.0, 2.0, 1.5, 4.0]))


def test_half_plane_polygon_returns_the_full_plate():
    """The half-plane counter-example of §5.1.3.3: directions parallel to a plate edge; plain
    Sutherland-Hodgman returns the empty set, the anchor rule the whole plate (area 15, 4 vertices)."""
    poly = [wall_point(-1, -1), wall_point(1, -1, w=2.0), wall_dir(1, 0), wall_dir(0, 1), wall_dir(-1, 0)]
    V, src = clip_wall(poly)
    assert V.shape[0] == 4 and np.all(V[:, 3] > 0)
    assert abs(frame_area(V) - 15.0) <= 1e-12
    X = V[:, :3] / V[:, 3:4]
    assert sorted(map(tuple, np.round(X, 12).tolist())) == sorted(map(tuple, WALL_BOUNDS.tolist()))
    assert ("bounds", 0, "anchor") in src


def test_270_degree_wedge_returns_the_full_plate():
    """The concave-prism counter-example (lamp in the notch): an arc at infinity spanning 270 degrees."""
    poly = [wall_point(-4, -1)]
    th0, delta = -0.5 * math.pi, 1.5 * math.pi
    steps = math.ceil(delta / math.radians(60) - 1e-12)
    for s in range(steps + 1):
        th = th0 + delta * s / steps
        poly.append(wall_dir(math.cos(th), math.sin(th)))
    V, _src = clip_wall(poly)
    assert V.shape[0] == 4
    assert abs(frame_area(V) - 15.0) <= 1e-12


def test_bounded_square_wedge_outside_and_nearly_parallel_direction():
    square = [wall_point(-1, 0.5), wall_point(1, 0.5, 3.0), wall_point(1, 1.5), wall_point(-1, 1.5)]
    V, src = clip_wall(square)
    assert V.shape[0] == 4 and src == [0, 1, 2, 3] and abs(frame_area(V) - 2.0) <= 1e-12
    # a < 180 degree wedge opening upwards from (0, 1): the triangle (0, 1), (1.5, 2.5), (-1.5, 2.5)
    wedge = [wall_point(0, 1), wall_dir(1, 1), wall_dir(0, 1), wall_dir(-1, 1)]
    V, _src = clip_wall(wedge)
    assert V.shape[0] == 3 and abs(frame_area(V) - 2.25) <= 1e-12
    # wholly outside the plate: empty
    outside = [wall_point(5, 0.5), wall_point(6, 0.5), wall_point(6, 1.5), wall_point(5, 1.5)]
    V, src = clip_wall(outside)
    assert V.shape == (0, 4) and src == []
    # directions nearly parallel to the bottom edge, pointing just below it: removed (strict >= 0)
    nearly = [wall_point(-1, 0.5), wall_dir(1, -1e-12), wall_dir(0, 1), wall_dir(-1, -1e-12)]
    V, _src = clip_wall(nearly)
    # no direction survives; the vertex (-1, 0.5) stays and the plate corners close the region
    assert np.all(V[:, 3] > 0) and V.shape[0] == 5 and abs(frame_area(V) - 12.0) <= 1e-9


def test_band_rule_keeps_a_vertex_on_a_plate_edge_without_a_duplicate():
    """A shadow vertex lying exactly on a plate edge (a fold point) is its own crossing."""
    tri = [wall_point(-1, 0), wall_point(1, -1), wall_point(1, 1)]
    V, src = clip_wall(tri)
    # (-1, 0) is on the bottom edge (band) and is kept with its own source; one crossing on (1,-1)->(1,1)
    assert src[0] == 0 and src[2] == 2 and sum(1 for s in src if isinstance(s, tuple)) == 1
    assert V.shape[0] == 3


def test_plate_loop_orientation_and_edge_on():
    L_front = np.array([0.0, 2.0, 3.0, 1.0])                 # positive side of the wall (y < 6)
    loop4, ids = plate_loop(WALL_BOUNDS, WALL_PI, L_front, 1e-9)
    assert ids == [0, 1, 2, 3] and np.allclose(loop4[:, :3], WALL_BOUNDS)
    loop4, ids = plate_loop(WALL_BOUNDS, WALL_PI, np.array([0.0, 9.0, 3.0, 1.0]), 1e-9)
    assert ids == [3, 2, 1, 0]
    assert plate_loop(WALL_BOUNDS, WALL_PI, np.array([0.0, 6.0, 3.0, 1.0]), 1e-9) is None


# --------------------------------------------------------------------------- wall_and_ground (§5.1.11 hand values)
import copy

from castplane.errors import warning_codes
from castplane.output.geometry_json import dumps


def wall_and_ground_scene() -> dict:
    """The hand-computed acceptance case of contract §5.1.11 (spec §10 M4)."""
    return {
        "version": "0.1", "units": "m", "up": "z",
        "objects": [{"id": "crate", "type": "box", "size": [1, 1, 1], "transform": {"position": [0, 4.5, 0]}}],
        "lights": [{"id": "lamp", "type": "point", "position": [0, 2, 3]}],
        "receivers": [{"id": "ground", "type": "plane", "normal": [0, 0, 1], "offset": 0},
                      {"id": "wall", "type": "plane", "normal": [0, -1, 0], "offset": 6,
                       "bounds": [[-3, 6, 0], [3, 6, 0], [3, 6, 2.5], [-3, 6, 2.5]]}],
        "camera": {"position": [0, -1, 1.6], "target": [0, 6, 0.8], "focal_length_mm": 35, "frame_mm": [36, 24]},
        "output": {"canvas_mm": [273, 182]},
    }


def fold_curved_cylinder_scene() -> dict:
    """A cylinder whose shadow folds from the ground onto the wall (conic bounds clip, §5.1.4)."""
    scene = wall_and_ground_scene()
    scene["objects"] = [{"id": "pillar", "type": "cylinder", "radius": 0.4, "height": 1.5,
                         "transform": {"position": [0, 5, 0]}}]
    return scene


def render(scene, **kw):
    return castplane.render(castplane.load_scene(scene), **kw)


def world(doc, name):
    return np.asarray(doc["points"][name]["world"], dtype=np.float64)


def shadow_of(doc, receiver, obj):
    found = [s for s in doc["shadows"] if s["receiver"] == receiver and s["object"] == obj]
    assert len(found) == 1, (receiver, obj)
    return found[0]


def test_wall_and_ground_hand_values():
    result = render(wall_and_ground_scene())
    doc = result["geometry"]
    assert doc["warnings"] == []
    assert doc["hidden_lines"] is False
    assert doc["receivers"] == [
        {"id": "ground", "plane": [0.0, 0.0, 1.0, 0.0], "bounds": None, "lit": {"lamp": True}, "casts": {"lamp": False}},
        {"id": "wall", "plane": [0.0, -1.0, 0.0, 6.0],
         "bounds": [[-3.0, 6.0, 0.0], [3.0, 6.0, 0.0], [3.0, 6.0, 2.5], [-3.0, 6.0, 2.5]],
         "lit": {"lamp": True}, "casts": {"lamp": True}}]
    # F.lamp, F.lamp.wall (exact)
    assert doc["points"]["F.lamp"]["world"] == [0.0, 2.0, 0.0]
    assert doc["points"]["F.lamp.wall"]["world"] == [0.0, 6.0, 3.0]
    # the crate: lit faces front (-y) and top; silhouette loop v0 v1 v5 v6 v7 v4
    A = castplane.shadow_geometry(castplane.load_scene(wall_and_ground_scene()))
    crate = A["objects"][0]
    normals = crate["mesh"]["face_normals"][crate["lights"]["lamp"]["lit"]]
    assert sorted(map(tuple, np.round(normals, 12).tolist())) == [(0.0, -1.0, 0.0), (0.0, 0.0, 1.0)]
    ground = shadow_of(doc, "ground", "crate")
    assert ground["outline"] == [f"crate.v{k}.shadow.lamp" for k in (0, 1, 5, 6, 7, 4)]
    expected_ground = {5: (0.75, 5, 0), 6: (0.75, 6.5, 0), 7: (-0.75, 6.5, 0), 4: (-0.75, 5, 0),
                       0: (-0.5, 4, 0), 1: (0.5, 4, 0)}
    for k, p in expected_ground.items():
        np.testing.assert_allclose(world(doc, f"crate.v{k}.shadow.lamp"), p, atol=1e-12)
    # wall shadow points (also outside the plate: genuine points of the plane)
    expected_wall = {6: (2 / 3, 6, 1 / 3), 7: (-2 / 3, 6, 1 / 3), 5: (1, 6, -1), 4: (-1, 6, -1),
                     0: (-1, 6, -3), 1: (1, 6, -3)}
    for k, p in expected_wall.items():
        np.testing.assert_allclose(world(doc, f"crate.v{k}.shadow.lamp.wall"), p, atol=1e-12)
    # the wall polygon after the bounds clip: (0.75,6,0) s0, (2/3,6,1/3), (-2/3,6,1/3), (-0.75,6,0) s1
    wall = shadow_of(doc, "wall", "crate")
    assert wall["outline"] == ["crate.s0.lamp.wall", "crate.v6.shadow.lamp.wall", "crate.v7.shadow.lamp.wall",
                               "crate.s1.lamp.wall"]
    assert wall["unbounded"] is False and len(wall["polygons"]) == 1 and len(wall["polygons"][0]) == 4
    np.testing.assert_allclose(world(doc, "crate.s0.lamp.wall"), (0.75, 6, 0), atol=1e-12)
    np.testing.assert_allclose(world(doc, "crate.s1.lamp.wall"), (-0.75, 6, 0), atol=1e-12)
    # the wall's own ground shadow: (-3,6,0), (3,6,0) band-kept, (18,26,0), (-18,26,0)
    plate = shadow_of(doc, "ground", "wall")
    assert plate["outline"] == [f"wall.b{k}.shadow.lamp" for k in range(4)]
    for k, p in enumerate([(-3, 6, 0), (3, 6, 0), (18, 26, 0), (-18, 26, 0)]):
        np.testing.assert_allclose(world(doc, f"wall.b{k}.shadow.lamp"), p, atol=1e-12)
    assert "OBJECT_BELOW_RECEIVER" not in warning_codes(doc["warnings"])
    # images (1e-6 mm)
    images = {"wall.b0": (-111.5758137, -29.5611244), "wall.b1": (111.5758137, -29.5611244),
              "wall.b2": (116.1978441, 65.4196009), "wall.b3": (-116.1978441, 65.4196009),
              "crate.s0.lamp.wall": (27.8939534, -29.5611244), "crate.s1.lamp.wall": (-27.8939534, -29.5611244),
              "crate.v6.shadow.lamp.wall": (24.9268280, -17.3359326),
              "crate.v7.shadow.lamp.wall": (-24.9268280, -17.3359326),
              "L.lamp": (0.0, 162.8814554), "F.lamp.wall": (0.0, 85.3679337), "F.lamp": (0.0, -104.8324357)}
    for name, uv in images.items():
        np.testing.assert_allclose(doc["points"][name]["image"], uv, atol=1e-6, err_msg=name)
    con = doc["construction"]
    np.testing.assert_allclose(con["light_point"], images["L.lamp"], atol=1e-6)
    np.testing.assert_allclose(con["shadow_vp"], images["F.lamp"], atol=1e-6)
    np.testing.assert_allclose(con["per_receiver"]["wall"]["shadow_vp"], images["F.lamp.wall"], atol=1e-6)


def _crossing_y(a, b, y):
    """Point of the segment a -> b at the given y."""
    t = (y - a[1]) / (b[1] - a[1])
    return a + t * (b - a)


def test_wall_and_ground_fold_points_agree_both_ways():
    """§5.1.3.4: the bounds-clip crossings of the wall polygon equal the crossings of the ground polygon's
    edges (0.75,5)->(0.75,6.5) and (-0.75,6.5)->(-0.75,5) with y = 6, and the literals (+-3/4, 6, 0)."""
    doc = render(wall_and_ground_scene())["geometry"]
    g = {k: world(doc, f"crate.v{k}.shadow.lamp") for k in (5, 6, 7, 4)}
    fold_right = _crossing_y(g[5], g[6], 6.0)
    fold_left = _crossing_y(g[7], g[4], 6.0)
    s0, s1 = world(doc, "crate.s0.lamp.wall"), world(doc, "crate.s1.lamp.wall")
    np.testing.assert_allclose(s0, fold_right, atol=1e-9)
    np.testing.assert_allclose(fold_right, s0, atol=1e-9)
    np.testing.assert_allclose(s1, fold_left, atol=1e-9)
    np.testing.assert_allclose(s0, (0.75, 6.0, 0.0), atol=1e-9)
    np.testing.assert_allclose(s1, (-0.75, 6.0, 0.0), atol=1e-9)
    # and the other way: the wall loop's edges through the fold lie on the ground plane's trace z = 0
    assert abs(s0[2]) <= 1e-9 and abs(s1[2]) <= 1e-9


def test_wall_and_ground_rays_only_inside_the_plate_and_construction_checks():
    doc = render(wall_and_ground_scene())["geometry"]
    pr = doc["construction"]["per_receiver"]["wall"]
    # only v6 and v7 have their wall shadow inside the plate
    assert pr["rays"] == [["L", "crate.v6"], ["F", "crate.v6.foot.wall"], ["L", "crate.v7"], ["F", "crate.v7.foot.wall"]]
    assert [c["point"] for c in pr["checks"]] == ["crate.v6.shadow.lamp.wall", "crate.v7.shadow.lamp.wall"]
    assert max(c["max_error_mm"] for c in pr["checks"]) <= 1e-6
    assert {s["kind"] for s in pr["segments"]} == {"LP", "FQ", "PQ"}
    # the flat block is the default receiver's (ground) only
    assert all(not r[1].endswith(".wall") for r in doc["construction"]["rays"])
    assert any(r[1].startswith("wall.b") for r in doc["construction"]["rays"])   # the plate's own rays
    # the SVG draws F'_wall and the wall's rays in the same three groups
    svg = render(wall_and_ground_scene())["svg"]
    assert "F′wall" in svg and 'id="construction.wall' not in svg


def test_wall_and_ground_svg_and_labels():
    svg = render(wall_and_ground_scene())["svg"]
    assert '<g id="objects.wall">' in svg and '<g id="objects.wall.front"' in svg
    assert ">b0</text>" in svg and 'font-weight="bold">wall</text>' in svg
    # no label for feet / shadows on the wall (a part "foot" / "shadow" after the first)
    assert ">v6.shadow.lamp.wall<" not in svg and ">v0.foot.wall<" not in svg and ">s0.lamp.wall<" not in svg
    # F.lamp.wall goes through the L/F branch and never becomes an object's top label
    assert ">F.lamp.wall</text>" in svg and 'font-weight="bold">F</text>' not in svg


def test_render_twice_is_byte_identical():
    for scene in (wall_and_ground_scene(), fold_curved_cylinder_scene()):
        r1, r2 = render(scene), render(scene)
        assert dumps(r1["geometry"]) == dumps(r2["geometry"]) and r1["svg"] == r2["svg"]


def test_fold_curved_cylinder():
    doc = render(fold_curved_cylinder_scene())["geometry"]
    assert doc["warnings"] == []
    wall = shadow_of(doc, "wall", "pillar")
    ground = shadow_of(doc, "ground", "pillar")
    assert wall["polygons"] and ground["polygons"] and not wall["unbounded"]
    # every vertex of the wall polygon lies on the wall plate
    names = [e for e in wall["outline"] if isinstance(e, str)]
    assert len(names) == len(wall["outline"])
    for n in names:
        assert n.endswith(".lamp.wall"), n
        p = world(doc, n)
        assert abs(p[1] - 6.0) <= 1e-9 and -3 - 1e-9 <= p[0] <= 3 + 1e-9 and -1e-9 <= p[2] <= 2.5 + 1e-9
    # the conic of the top cap on the wall is bounds-clipped in closed form: its arc lies on the plate
    assert wall["conics"] and all(c["map"] == "shadow" for c in wall["conics"])
    A = castplane.shadow_geometry(castplane.load_scene(fold_curved_cylinder_scene()))
    cd = A["objects"][0]["curved"]["wall"]["lamp"]
    assert set(A["objects"][0]["curved"]) == {"ground", "wall"}
    for piece in cd["conic_pieces"]:
        ca = piece["conic_arc"]
        th = np.linspace(ca["theta0"], ca["theta1"], 33)
        from castplane.conics import conic_point
        X = conic_point(ca["E"], th, ca["rho"]) @ np.asarray(ca["T"]).T
        Xw = X[:, :3] / X[:, 3:4]
        assert np.all(np.abs(Xw[:, 1] - 6.0) <= 1e-9) and np.all(Xw[:, 2] >= -1e-9) and np.all(Xw[:, 2] <= 2.5 + 1e-9)
    # fold: the ground polygon's crossing of y = 6 at the base line z = 0 agrees with the wall's s-points at z = 0
    on_base = sorted(world(doc, n)[0] for n in names if abs(world(doc, n)[2]) <= 1e-12)
    assert len(on_base) == 2
    G = np.array([world(doc, n) for n in ground["outline"] if isinstance(n, str)])
    xs = []
    for a, b in zip(G, np.roll(G, -1, axis=0)):
        if (a[1] - 6.0) * (b[1] - 6.0) < 0:
            xs.append(_crossing_y(a, b, 6.0)[0])
    assert len(xs) == 2
    # the ground polygon is the 64-gon sample of the same conic: the fold x agree to the sampling chord error
    np.testing.assert_allclose(sorted(xs), on_base, atol=5e-3)


# --------------------------------------------------------------------------- RECEIVER_UNLIT and other degenerate cases
def unlit_codes(doc):
    return {tuple(w["ids"]): w["message"] for w in doc["warnings"] if w["code"] == "RECEIVER_UNLIT"}


@pytest.mark.parametrize("case, light, message", [
    ("point behind", {"id": "lamp", "type": "point", "position": [0, 8, 3]}, "point light is behind"),
    ("point in plane", {"id": "lamp", "type": "point", "position": [0, 6, 3]}, "point light is behind"),
    ("directional parallel", {"id": "lamp", "type": "directional", "direction": [0.6, 0.0, 0.8]}, "parallel"),
    ("directional behind", {"id": "lamp", "type": "directional", "direction": [0.0, 0.6, 0.8]}, "behind"),
    ("below the ground", {"id": "lamp", "type": "point", "position": [0, 2, -1]}, "light below the ground"),
    ("sun below the ground", {"id": "lamp", "type": "directional", "direction": [0.0, -0.6, -0.8]},
     "light below the ground"),
])
def test_receiver_unlit_predicates(case, light, message):
    scene = wall_and_ground_scene()
    scene["lights"] = [light]
    doc = render(scene)["geometry"]
    codes = unlit_codes(doc)
    assert set(codes) == {("lamp", "wall")}, (case, doc["warnings"])
    assert message in codes[("lamp", "wall")]
    wall = shadow_of(doc, "wall", "crate")
    assert wall["loops"] == [] and wall["polygons"] == [] and not wall["unbounded"]
    receivers = {r["id"]: r for r in doc["receivers"]}
    assert receivers["wall"]["lit"] == {"lamp": False}
    assert doc["construction"]["per_receiver"]["wall"]["rays"] == []
    if "ground" in message:
        # the ground is opaque: no plate casts
        assert receivers["wall"]["casts"] == {"lamp": False}
        assert "LIGHT_BELOW_RECEIVER" in warning_codes(doc["warnings"])
        assert shadow_of(doc, "ground", "wall")["loops"] == []


def test_horizontal_sun_lights_the_wall():
    """DIRECTIONAL_HORIZONTAL on the ground does not propagate (a horizontal sun lights walls)."""
    scene = wall_and_ground_scene()
    scene["lights"] = [{"id": "sun", "type": "directional", "direction": [0.0, -1.0, 0.0]}]
    doc = render(scene)["geometry"]
    assert ("DIRECTIONAL_HORIZONTAL", ("sun",)) in {(w["code"], tuple(w["ids"])) for w in doc["warnings"]}
    assert not unlit_codes(doc)
    wall = shadow_of(doc, "wall", "crate")
    assert len(wall["polygons"]) == 1 and len(wall["polygons"][0]) == 4
    # light along the wall normal: the foot on the wall is undefined (F.sun.wall absent, shadow_vp null)
    assert "F.sun.wall" not in doc["points"]
    pr = doc["construction"]["per_receiver"]["wall"]
    assert pr["shadow_vp"] is None and pr["shadow_vp_at_infinity"] is None
    assert all(kind == "L" for kind, _n in pr["rays"]) and pr["rays"]


def test_directional_wall_shadow_vp_at_infinity_ids():
    scene = wall_and_ground_scene()
    d = np.array([0.3, -0.5, 0.8]) / math.sqrt(0.98)
    scene["lights"] = [{"id": "sun", "type": "directional", "direction": d.tolist()}]
    scene["camera"] = {"position": [0, -1, 1.6], "target": [0, 6, 1.6], "focal_length_mm": 35, "frame_mm": [36, 24]}
    doc = render(scene)["geometry"]
    pairs = {(w["code"], tuple(w["ids"])) for w in doc["warnings"]}
    assert ("SHADOW_VP_AT_INFINITY", ("sun", "wall")) in pairs
    assert ("SHADOW_VP_AT_INFINITY", ("sun",)) not in pairs
    pr = doc["construction"]["per_receiver"]["wall"]
    assert pr["shadow_vp"] is None and pr["shadow_vp_at_infinity"] is not None
    assert doc["points"]["F.sun.wall"]["at_infinity"] is True
    assert doc["construction"]["shadow_vp"] is not None


def test_plate_edge_on_to_the_light_and_seen_edge_on():
    scene = wall_and_ground_scene()
    scene["lights"] = [{"id": "lamp", "type": "point", "position": [0, 6, 3]}]        # in the wall plane
    doc = render(scene)["geometry"]
    assert {r["id"]: r["casts"] for r in doc["receivers"]}["wall"] == {"lamp": False}
    assert shadow_of(doc, "ground", "wall")["loops"] == []
    scene = wall_and_ground_scene()
    scene["camera"] = {"position": [-6, 6, 1.6], "target": [0, 6, 1.0], "focal_length_mm": 35, "frame_mm": [36, 24]}
    result = render(scene)                                                          # camera in the wall plane
    doc = result["geometry"]
    assert all(math.isfinite(x) for x in _numbers(doc))
    assert not any(f["object"] == "wall" for f in doc["form_shadow"])


def _numbers(obj):
    if isinstance(obj, dict):
        for v in obj.values():
            yield from _numbers(v)
    elif isinstance(obj, list):
        for v in obj:
            yield from _numbers(v)
    elif isinstance(obj, float):
        yield obj


def test_plate_form_shadow_when_the_camera_sees_the_unlit_face():
    scene = wall_and_ground_scene()
    scene["camera"] = {"position": [1, 12, 1.6], "target": [0, 4, 0.8], "focal_length_mm": 35, "frame_mm": [36, 24]}
    doc = render(scene)["geometry"]
    plates = [f for f in doc["form_shadow"] if f["object"] == "wall"]
    assert len(plates) == 1 and plates[0]["faces"] == [["wall.b0", "wall.b1", "wall.b2", "wall.b3"]]
    assert plates[0]["terminator"] == [] and len(plates[0]["polygons"]) == 1
    # entries are in document order: objects first, then the plates
    assert doc["form_shadow"][-1]["object"] == "wall"


def test_crate_straddling_the_wall_is_clipped_silently():
    scene = wall_and_ground_scene()
    scene["objects"][0]["transform"]["position"] = [0, 6.0, 0]       # half of the crate behind the wall
    doc = render(scene)["geometry"]
    codes = warning_codes(doc["warnings"])
    assert "OBJECT_BELOW_RECEIVER" not in codes and "VERTEX_NOT_BELOW_LIGHT" not in codes
    wall = shadow_of(doc, "wall", "crate")
    names = [n for loop in wall["loops"] for n in loop]
    assert names and all(isinstance(n, str) for n in names)
    assert len(names) == len(set(names))                              # no duplicate s<k> at the plate edge
    s_points = [n for n in names if ".s" in n]
    assert s_points and all(n.endswith(".lamp.wall") for n in s_points)
    for n in names:
        p = world(doc, n)
        assert abs(p[1] - 6.0) <= 1e-9 and p[2] >= -1e-9


def test_coplanar_caster_casts_nothing():
    scene = wall_and_ground_scene()
    scene["receivers"].append({"id": "tile", "type": "plane", "normal": [0, -1, 0], "offset": 6,
                               "bounds": [[3, 6, 0], [5, 6, 0], [5, 6, 2.5], [3, 6, 2.5]]})
    doc = render(scene)["geometry"]
    assert shadow_of(doc, "wall", "tile")["loops"] == [] and shadow_of(doc, "tile", "wall")["loops"] == []
    # ... while each still casts on the ground
    assert shadow_of(doc, "ground", "tile")["loops"] and shadow_of(doc, "ground", "wall")["loops"]
    assert doc["warnings"] == []
    order = [(s["receiver"], s["object"]) for s in doc["shadows"]]
    assert order == [("ground", "crate"), ("ground", "wall"), ("ground", "tile"),
                     ("wall", "crate"), ("wall", "tile"), ("tile", "crate"), ("tile", "wall")]


def test_bounded_default_receiver():
    """No ground: receivers[0] is a floor plate; it owns the short names and the flat construction keys."""
    scene = wall_and_ground_scene()
    scene["receivers"] = [{"id": "floor", "type": "plane", "normal": [0, 0, 1], "offset": 0,
                           "bounds": [[-2, 2, 0], [2, 2, 0], [2, 5.5, 0], [-2, 5.5, 0]]}]
    doc = render(scene)["geometry"]
    assert doc["warnings"] == []
    floor = shadow_of(doc, "floor", "crate")
    assert floor["unbounded"] is False and floor["polygons"]
    assert all(isinstance(n, str) and not n.endswith(".floor") for n in floor["outline"])
    assert "crate.s0.lamp" in floor["outline"]                     # clipped at y = 5.5 by the bounds
    for n in floor["outline"]:
        assert world(doc, n)[1] <= 5.5 + 1e-9
    assert doc["construction"]["per_receiver"] == {}
    assert doc["construction"]["rays"]
    assert doc["receivers"][0]["bounds"] is not None


def test_concave_prism_on_plate_anchor_rule():
    """U-prism with the lamp in the notch on a bounded floor plate: the arc at infinity spans more than
    180 degrees and the anchor rule gives the whole plate (§5.1.3.3, the counter-example of D22)."""
    scene = wall_and_ground_scene()
    scene["objects"] = [{"id": "u", "type": "prism", "height": 1.0,
                         "polygon": [[-1, -1], [1, -1], [1, 1], [0.5, 1], [0.5, -0.5], [-0.5, -0.5], [-0.5, 1],
                                     [-1, 1]],
                         "transform": {"position": [0, 0, 0]}}]
    scene["lights"] = [{"id": "lamp", "type": "point", "position": [0, 0.2, 0.7]}]
    # the plate lies behind the back arm of the U, wholly in its shadow (the lamp is below the arms' tops)
    scene["receivers"] = [{"id": "plate", "type": "plane", "normal": [0, 0, 1], "offset": 0,
                           "bounds": [[-3, -4.5, 0], [3, -4.5, 0], [3, -2, 0], [-3, -2, 0]]}]
    scene["camera"] = {"position": [0, 4, 4], "target": [0, -3, 0], "focal_length_mm": 35, "frame_mm": [36, 24]}
    doc = render(scene)["geometry"]
    sh = shadow_of(doc, "plate", "u")
    assert not sh["unbounded"] and sh["polygons"]
    pts = [world(doc, n)[:2] for loop in sh["loops"] for n in loop]
    area = sum(0.5 * abs(_shoelace(np.array([world(doc, n)[:2] for n in loop]))) for loop in sh["loops"])
    assert abs(area - 15.0) <= 1e-9, (sh["loops"], area)
    assert all(-3 - 1e-9 <= p[0] <= 3 + 1e-9 and -4.5 - 1e-9 <= p[1] <= -2 + 1e-9 for p in pts)
    # the unclipped shadow polygon is unbounded with an arc at infinity spanning more than 180 degrees
    A = castplane.shadow_geometry(castplane.load_scene(scene))
    rec = next(r for r in A["shadows"] if r["object"] == "u")
    assert any(isinstance(s, tuple) and s[-1] == "anchor" for loop in rec["loops"] for s in loop["sources"])


def _shoelace(uv):
    x, y = uv[:, 0], uv[:, 1]
    return float(np.sum(x * np.roll(y, -1) - np.roll(x, -1) * y))


# --------------------------------------------------------------------------- frame equivalence (§5.1.2)
def _rx90(p):
    """Rotation by +90 degrees about x: (x, y, z) -> (x, -z, y); maps the floor z = 0 (normal +z) onto
    the wall y = 0 with normal (0, -1, 0), and the floor frame (x, y) onto the wall frame (x, z)."""
    x, y, z = p
    return [x, -z, y]


def _floor_and_wall_scenes(obj: dict, lamp):
    floor_bounds = [[-3, -3, 0], [3, -3, 0], [3, 3, 0], [-3, 3, 0]]
    cam = {"position": [0, -8, 6], "target": [0, 0, 0], "focal_length_mm": 35, "frame_mm": [36, 24]}
    floor = {"version": "0.1", "objects": [obj], "lights": [{"id": "lamp", "type": "point", "position": lamp}],
             "receivers": [{"id": "plate", "type": "plane", "normal": [0, 0, 1], "offset": 0, "bounds": floor_bounds}],
             "camera": cam, "output": {"canvas_mm": [36, 24]}}
    wall = copy.deepcopy(floor)
    wobj = wall["objects"][0]
    wobj["transform"] = {"position": _rx90(obj["transform"]["position"]), "rotation_deg": [90, 0, 0]}
    wall["lights"][0]["position"] = _rx90(lamp)
    wall["receivers"][0].update({"normal": [0, -1, 0], "bounds": [_rx90(p) for p in floor_bounds]})
    wall["camera"] = {"position": _rx90(cam["position"]), "target": _rx90(cam["target"]),
                      "focal_length_mm": 35, "frame_mm": [36, 24]}
    return floor, wall


@pytest.mark.parametrize("obj, lamp", [
    ({"id": "c", "type": "cylinder", "radius": 0.5, "height": 1.5, "transform": {"position": [0.3, -0.2, 0]}},
     [1.4, 0.3, 1.0]),                                        # lamp below the top: unbounded before the clip
    ({"id": "s", "type": "sphere", "radius": 0.6, "transform": {"position": [-0.4, 0.2, 0]}}, [0.9, -0.6, 0.8]),
    ({"id": "b", "type": "box", "size": [0.8, 0.6, 1.4], "transform": {"position": [0.2, 0.1, 0]}}, [1.2, 0.9, 1.0]),
])
def test_frame_equivalence_wall_rotated_to_ground(obj, lamp):
    """A cylinder / sphere / box on a wall, lamp below the top, against the scene rotated so that the wall
    becomes the floor: the shadow polygons agree within 1e-9 m and carry the same names."""
    floor, wall = _floor_and_wall_scenes(obj, lamp)
    df = render(floor)["geometry"]
    dw = render(wall)["geometry"]
    sf, sw = shadow_of(df, "plate", obj["id"]), shadow_of(dw, "plate", obj["id"])
    assert sf["loops"] and len(sf["loops"]) == len(sw["loops"])
    if obj["type"] == "sphere":
        # the sphere's silhouette-circle frame is e1 = normalize(n × z) with the world z (contract §2.6), which a
        # rotation about x does not carry along: the 64 samples start at a different point of the same exact
        # curve, so the polygons are compared as curves (implementation note of §5.1.11)
        for lf, lw in zip(sf["loops"], sw["loops"]):
            Pf = np.array([_rx90(world(df, n)) for n in lf])
            Pw = np.array([world(dw, n) for n in lw])
            assert abs(len(Pf) - len(Pw)) <= 2
            sagitta = 2.0 * float(np.max(np.linalg.norm(Pf - Pf.mean(axis=0), axis=1))) * (1 - math.cos(math.pi / 64))
            for P, Q in ((Pf, Pw), (Pw, Pf)):
                for p in P:
                    assert _distance_to_polygon(p, Q) <= sagitta + 1e-9
            assert abs(_shoelace(Pf[:, [0, 2]]) - _shoelace(Pw[:, [0, 2]])) <= 1e-3 * abs(_shoelace(Pf[:, [0, 2]]))
        return
    assert sf["loops"] == sw["loops"]
    for loop in sf["loops"]:
        for n in loop:
            np.testing.assert_allclose(_rx90(world(df, n)), world(dw, n), atol=1e-9, err_msg=n)
    A_f = castplane.shadow_geometry(castplane.load_scene(floor))
    A_w = castplane.shadow_geometry(castplane.load_scene(wall))
    for rf, rw in zip(A_f["shadows"], A_w["shadows"]):
        for lf, lw in zip(rf["loops"], rw["loops"]):
            Vf, Vw = np.asarray(lf["vertices"]), np.asarray(lw["vertices"])
            assert Vf.shape == Vw.shape
            Xf = Vf[:, :3] / Vf[:, 3:4]
            Xw = Vw[:, :3] / Vw[:, 3:4]
            np.testing.assert_allclose(np.array([_rx90(p) for p in Xf]), Xw, atol=1e-9)
    # the unclipped curved polygon (built in the receiver frame) is unbounded and rotates exactly as well
    if obj["type"] == "cylinder":
        cf = A_f["objects"][0]["curved"]["plate"]["lamp"]["outline"]
        assert cf["unbounded"]


def _distance_to_polygon(p, Q) -> float:
    best = math.inf
    for a, b in zip(Q, np.roll(Q, -1, axis=0)):
        ab = b - a
        t = 0.0 if not float(ab @ ab) else min(1.0, max(0.0, float((p - a) @ ab) / float(ab @ ab)))
        best = min(best, float(np.linalg.norm(a + t * ab - p)))
    return best


# --------------------------------------------------------------------------- spec §7.3 on plates (raycast IoU >= 0.99)
from castplane.shadow import receiver_frame as _frame
from tests.reference import random_scenes, raster, raycast


def plate_masks(scene: dict, doc: dict, rid: str, n_u: int = 480):
    """(document mask, ray-cast mask) on the plate ``rid`` in its frame coordinates: the union over the
    shadow records on ``rid`` of the nonzero-rasterised loops, against ``raycast.occluded_on_receiver`` from
    the plate samples; both restricted to the plate."""
    rcv = next(r for r in scene["receivers"] if r["id"] == rid)
    n = np.asarray(rcv["normal"], dtype=np.float64)
    e1, e2 = _frame(n)
    B = np.asarray(rcv["bounds"], dtype=np.float64)
    uv_b = np.stack([B @ e1, B @ e2], axis=1)
    lo, hi = uv_b.min(axis=0), uv_b.max(axis=0)
    h = float(hi[0] - lo[0]) / n_u
    us = lo[0] + h * (np.arange(n_u) + 0.5)
    vs = lo[1] + h * (np.arange(int(math.ceil((hi[1] - lo[1]) / h))) + 0.5)
    on_plate = raster.rasterize_polygons([uv_b], us, vs)
    mask_doc = np.zeros(on_plate.shape, dtype=bool)
    for sh in doc["shadows"]:
        if sh["receiver"] != rid:
            continue
        loops = []
        for loop in sh["loops"]:
            P = np.array([doc["points"][e]["world"] for e in loop], dtype=np.float64)
            loops.append(np.stack([P @ e1, P @ e2], axis=1))
        if loops:
            mask_doc |= raster.rasterize_polygons(loops, us, vs)
    U, V = np.meshgrid(us, vs)
    base = -float(rcv.get("offset", 0.0)) * n                      # a point of the plane
    origins = base[None, :] + U.ravel()[:, None] * e1[None, :] + V.ravel()[:, None] * e2[None, :]
    mask_ref = raycast.occluded_on_receiver(scene, scene["lights"][0], rid, origins).reshape(U.shape)
    return mask_doc & on_plate, mask_ref & on_plate


def random_plate_scene(seed: int) -> dict:
    """A seeded random §7.3 scene (point light) with a wall plate behind the objects and a floor tile."""
    scene = random_scenes.make_scene(seed, 3, "point")
    pts = np.vstack([random_scenes.world_extreme_points(o) for o in scene["objects"]])
    y_wall = float(pts[:, 1].max()) + 0.5
    x0, x1 = float(pts[:, 0].min()) - 4.0, float(pts[:, 0].max()) + 4.0
    scene["receivers"].append({"id": "wall", "type": "plane", "normal": [0, -1, 0], "offset": y_wall,
                               "bounds": [[x0, y_wall, 0], [x1, y_wall, 0], [x1, y_wall, 3.0], [x0, y_wall, 3.0]]})
    # the lamp in front of the objects, a little above their tops, so that they cast onto the wall
    rng = np.random.default_rng(seed)
    scene["lights"][0]["position"] = [float(pts[:, 0].mean() + rng.uniform(-1.0, 1.0)),
                                      float(pts[:, 1].min()) - float(rng.uniform(1.0, 3.0)),
                                      float(pts[:, 2].max()) + float(rng.uniform(0.2, 1.5))]
    return scene


def _iou_scenes():
    scenes = [("wall_and_ground", wall_and_ground_scene(), "wall"),
              ("fold_curved_cylinder", fold_curved_cylinder_scene(), "wall")]
    floor = wall_and_ground_scene()
    floor["receivers"] = [{"id": "floor", "type": "plane", "normal": [0, 0, 1], "offset": 0,
                           "bounds": [[-2, 2, 0], [2, 2, 0], [2, 5.5, 0], [-2, 5.5, 0]]},
                          dict(wall_and_ground_scene()["receivers"][1])]
    scenes.append(("bounded floor + wall (floor)", floor, "floor"))
    scenes.append(("bounded floor + wall (wall)", floor, "wall"))
    for seed in range(8):
        scenes.append((f"random {seed}", random_plate_scene(seed), "wall"))
    return scenes


@pytest.mark.parametrize("label, scene, rid", _iou_scenes(), ids=[s[0] for s in _iou_scenes()])
def test_raycast_iou_on_plates(label, scene, rid):
    validated = castplane.load_scene(scene)
    doc = castplane.render(validated)["geometry"]
    mask_doc, mask_ref = plate_masks(validated, doc, rid)
    if not mask_ref.any() and not mask_doc.any():
        return
    assert raster.iou(mask_doc, mask_ref) >= 0.99, (label, raster.iou(mask_doc, mask_ref),
                                                    int(mask_doc.sum()), int(mask_ref.sum()))


# --------------------------------------------------------------------------- spec §7.1 rows 1-6 (§5.1.11)
from tests.test_invariants import assert_images_equal, meet_lines, transform_scene

INVARIANT_SCENES = [("wall_and_ground", wall_and_ground_scene), ("fold_curved_cylinder", fold_curved_cylinder_scene)]


def _h(p):
    return np.array([p[0], p[1], 1.0])


@pytest.mark.parametrize("label, make", INVARIANT_SCENES)
def test_row1_construction_equals_direct_projection(label, make):
    doc = render(make())["geometry"]
    con = doc["construction"]
    Lp = _h(con["light_point"])
    blocks = [(con, "", con["shadow_vp"])] + [(blk, f".{rid}", blk["shadow_vp"])
                                               for rid, blk in con["per_receiver"].items()]
    verified = 0
    for blk, sfx, fp in blocks:
        assert blk["checks"] and max(c["max_error_mm"] for c in blk["checks"]) <= 1e-6
        Fp = _h(fp)
        for kind, name in blk["rays"]:
            if kind != "L":
                continue
            P = doc["points"][name]["image"]
            S = doc["points"][f"{name}.shadow.lamp{sfx}"]["image"]
            Q = doc["points"][f"{name}.foot{sfx}"]["image"]
            s_check = meet_lines(Lp, _h(P), Fp, _h(Q))
            np.testing.assert_allclose(s_check[:2] / s_check[2], S, atol=1e-6)
            verified += 1
    assert verified >= 4


@pytest.mark.parametrize("label, make", INVARIANT_SCENES)
def test_row2_all_receivers_shadow_points_are_camera_independent(label, make):
    scene = make()
    doc1 = render(scene)["geometry"]
    cam2 = {"position": [-5.0, -3.0, 4.0], "target": [0.0, 5.0, 0.5], "roll_deg": 8.0, "focal_length_mm": 24.0,
            "frame_mm": [36, 24], "shift_mm": [1.0, -2.0], "near_m": 0.1}
    doc2 = render(scene, camera=cam2)["geometry"]
    assert doc1["camera"]["P"] != doc2["camera"]["P"]
    names = {n for n in doc1["points"] if ".og" not in n}
    assert names == {n for n in doc2["points"] if ".og" not in n}
    assert any(n.endswith(".wall") for n in names)
    for n in names:
        key = "world" if "world" in doc1["points"][n] else "direction"
        np.testing.assert_allclose(doc1["points"][n][key], doc2["points"][n][key], atol=1e-9, err_msg=n)
    assert [s["loops"] for s in doc1["shadows"]] == [s["loops"] for s in doc2["shadows"]]
    assert [(s["receiver"], s["object"], s["unbounded"]) for s in doc1["shadows"]] == \
        [(s["receiver"], s["object"], s["unbounded"]) for s in doc2["shadows"]]
    assert doc1["receivers"] == doc2["receivers"]
    for s1, s2 in zip(doc1["shadows"], doc2["shadows"]):
        assert [(c["circle"], c["arc"]) for c in s1["conics"]] == [(c["circle"], c["arc"]) for c in s2["conics"]]


@pytest.mark.parametrize("label, make", INVARIANT_SCENES)
def test_row3_point_light_converges_to_directional_on_the_wall(label, make):
    d = np.array([0.25, -0.55, 0.8])
    d = d / np.linalg.norm(d)
    scene_d = make()
    scene_d["lights"] = [{"id": "lamp", "type": "directional", "direction": d.tolist()}]
    doc_d = render(scene_d)["geometry"]
    wall_names = [n for n in doc_d["points"] if ".shadow.lamp.wall" in n]
    assert wall_names
    gaps = {}
    for D in (1e6, 1e7):
        scene_p = make()
        scene_p["lights"] = [{"id": "lamp", "type": "point", "position": (D * d).tolist()}]
        doc_p = render(scene_p)["geometry"]
        assert [s["loops"] for s in doc_d["shadows"]] == [s["loops"] for s in doc_p["shadows"]]
        for n in wall_names:
            gap = float(np.linalg.norm(np.subtract(doc_p["points"][n]["world"], doc_d["points"][n]["world"])))
            assert gap <= 1e-4, (n, D, gap)
            gaps.setdefault(n, {})[D] = gap
    for n, g in gaps.items():
        assert g[1e7] <= 0.1 * g[1e6] + 1e-9, (n, g)


def _transform_receivers(scene, angle_deg, shift):
    a = math.radians(angle_deg)
    R = np.array([[math.cos(a), -math.sin(a), 0.0], [math.sin(a), math.cos(a), 0.0], [0.0, 0.0, 1.0]])
    t = np.array([shift[0], shift[1], 0.0])
    for r in scene["receivers"]:
        if r.get("bounds") is None:
            continue
        n = R @ np.asarray(r["normal"], dtype=np.float64)
        r["bounds"] = [(R @ np.asarray(b, dtype=np.float64) + t).tolist() for b in r["bounds"]]
        r["normal"] = n.tolist()
        r["offset"] = float(r["offset"]) - float(n @ t)
    return scene


@pytest.mark.parametrize("label, make", INVARIANT_SCENES)
@pytest.mark.parametrize("yaw_form", [False, True])
def test_row4_rigid_equivariance_with_bounds(label, make, yaw_form):
    scene = castplane.load_scene(make())
    doc1 = castplane.render(scene)["geometry"]
    for angle, shift in ((37.0, (2.5, -1.25)), (-120.0, (-4.0, 3.0)), (180.0, (0.0, 0.0))):
        moved = _transform_receivers(transform_scene(scene, angle, shift, yaw_form), angle, shift)
        doc2 = castplane.render(castplane.load_scene(moved))["geometry"]
        assert_images_equal(doc1, doc2, 1e-6)
        pr1, pr2 = doc1["construction"]["per_receiver"], doc2["construction"]["per_receiver"]
        assert set(pr1) == set(pr2)
        for rid in pr1:
            assert pr1[rid]["rays"] == pr2[rid]["rays"]
            np.testing.assert_allclose(pr1[rid]["shadow_vp"], pr2[rid]["shadow_vp"], atol=1e-6)
            for s1, s2 in zip(pr1[rid]["segments"], pr2[rid]["segments"]):
                scale = max(1.0, max(abs(x) for p in s1["points"] for x in p))
                np.testing.assert_allclose(s1["points"], s2["points"], atol=1e-6 * scale)


@pytest.mark.parametrize("k_pi, k_L, k_P", [(2.0, 3.0, 0.5), (1e-3, 1e3, 7.0), (5.0, 0.25, 1e2)])
def test_row5_scale_invariance_of_the_receiver_helpers(k_pi, k_L, k_P):
    """Row 5 at the helper level (contract §4): shadow_loop in the wall frame with positively scaled pi, L and
    loop points, and clip_polygon_bounds with positively scaled vertices, give the same divided polygons."""
    from castplane.light import light_vector
    from castplane.shadow import shadow_loop, shadow_matrix
    psi = bounds_functionals(WALL_BOUNDS, WALL_N)
    frame = receiver_frame(WALL_N)
    for light in ({"id": "lamp", "type": "point", "position": [0.0, 4.3, 1.2]},     # unbounded on the wall plane
                  {"id": "lamp", "type": "directional", "direction": [0.0, -0.9, math.sqrt(0.19)]}):
        scene = wall_and_ground_scene()
        scene["lights"] = [light]
        A = castplane.shadow_geometry(castplane.load_scene(scene))
        crate = A["objects"][0]
        (loop_ids,) = crate["lights"]["lamp"]["loops"]
        V = crate["mesh"]["vertices"][loop_ids]
        loop = np.concatenate([V, np.ones((V.shape[0], 1))], axis=1)
        Lv = light_vector(light)
        M1, M2 = shadow_matrix(WALL_PI, Lv), shadow_matrix(k_pi * WALL_PI, k_L * Lv)
        sh1 = shadow_loop(loop, M1, WALL_PI, 1e-9, frame=frame)
        sh2 = shadow_loop(k_P * loop, M2, k_pi * WALL_PI, k_pi * 1e-9, tol_clip=k_pi * 1e-9, frame=frame)
        V1, V2 = sh1["vertices"], sh2["vertices"]
        assert V1.shape == V2.shape
        n1 = V1 / np.max(np.abs(V1), axis=1, keepdims=True)
        n2 = V2 / np.max(np.abs(V2), axis=1, keepdims=True)
        np.testing.assert_allclose(n1, n2, rtol=1e-9, atol=1e-9)
        C1, _s1 = clip_polygon_bounds(V1, sh1["sources"], psi, WALL_BOUNDS, 1e-9)
        scales = np.linspace(0.5, 4.0, V1.shape[0])[:, None]
        C2, _s2 = clip_polygon_bounds(V1 * scales, sh1["sources"], psi, WALL_BOUNDS, 1e-9)
        assert C1.shape == C2.shape and C1.shape[0] >= 3
        np.testing.assert_allclose(C1[:, :3] / C1[:, 3:4], C2[:, :3] / C2[:, 3:4], rtol=1e-9, atol=1e-9)
        if light["type"] == "point":
            assert sh1["unbounded"]


@pytest.mark.parametrize("label, make", INVARIANT_SCENES + [
    ("unlit", lambda: dict(wall_and_ground_scene(), lights=[{"id": "lamp", "type": "point", "position": [0, 9, 3]}])),
    ("low lamp", lambda: dict(wall_and_ground_scene(), lights=[{"id": "lamp", "type": "point", "position": [0, 2, 0.6]}])),
    ("camera behind the wall", lambda: dict(wall_and_ground_scene(), camera={
        "position": [0.5, 9, 1.0], "target": [0, 3, 0.5], "focal_length_mm": 20, "frame_mm": [36, 24]})),
])
def test_row6_no_nan_or_inf(label, make):
    import re
    result = render(make())
    text = dumps(result["geometry"])
    assert "NaN" not in text and "Infinity" not in text and not re.search(r"-0\.0(?![0-9])", text)
    assert all(math.isfinite(x) for x in _numbers(result["geometry"]))
    low = result["svg"].lower().replace("infinity", "")
    assert "nan" not in low and "inf" not in low


# --------------------------------------------------------------------------- review fixes: unique SVG ids
def curved_on_wall_scene() -> dict:
    """A sphere, a cylinder and a cone in front of the wall: each casts conics on the ground and on the wall."""
    scene = wall_and_ground_scene()
    scene["objects"] = [
        {"id": "ball", "type": "sphere", "radius": 0.35, "transform": {"position": [-1.2, 5.0, 0.35]}},
        {"id": "pillar", "type": "cylinder", "radius": 0.3, "height": 1.2, "transform": {"position": [0.0, 5.1, 0]}},
        {"id": "spire", "type": "cone", "radius": 0.35, "height": 1.0, "transform": {"position": [1.2, 5.0, 0]}},
    ]
    return scene


@pytest.mark.parametrize("label, make", [("wall_and_ground", wall_and_ground_scene),
                                         ("fold_curved_cylinder", fold_curved_cylinder_scene),
                                         ("curved_on_wall", curved_on_wall_scene)])
def test_svg_ids_are_unique_with_several_receivers(label, make):
    """XML ids are unique (§2.10 'exact ids'): an object casting conics on several receivers gets one
    ``cast_shadow.<light>.<object>.conics`` group on receivers[0] and ``.<receiver>.conics`` on every other one."""
    import collections
    import re
    result = render(make())
    ids = re.findall(r'\sid="([^"]*)"', result["svg"])
    dup = [k for k, n in collections.Counter(ids).items() if n > 1]
    assert dup == [], (label, dup)
    # hidden lines on: the .outline groups follow the same per-receiver scheme (polyhedra included)
    hidden_ids = re.findall(r'\sid="([^"]*)"', render(make(), hidden_lines=True)["svg"])
    dup = [k for k, n in collections.Counter(hidden_ids).items() if n > 1]
    assert dup == [], (label, "hidden lines", dup)
    assert any(i.endswith(".wall.outline") for i in hidden_ids), label
    receivers = {s["receiver"] for s in result["geometry"]["shadows"] if s.get("conics")}
    if label != "wall_and_ground":
        assert receivers == {"ground", "wall"}
        assert "cast_shadow.lamp.pillar.conics" in ids and "cast_shadow.lamp.pillar.wall.conics" in ids


def test_hidden_bridge_only_tolerates_the_missing_module(monkeypatch):
    """The A-track import bridge is gone now that the H-track has landed (contract §5.1.6.5): ``compose`` with
    hidden lines on calls ``castplane.hidden.classify_document(doc, B["A"], B)`` directly, an error raised
    inside it propagates, and with hidden lines off it is never called."""
    from castplane import hidden, pipeline

    calls = []

    def spy(doc, A, B, *a, **k):
        calls.append((A is B["A"], doc["hidden_lines"]))
        raise RuntimeError("inside classify_document")

    monkeypatch.setattr(hidden, "classify_document", spy)
    scene = castplane.load_scene(wall_and_ground_scene())
    A = castplane.shadow_geometry(scene)
    B = castplane.project_scene(scene, A)
    with pytest.raises(RuntimeError, match="inside classify_document"):
        pipeline.compose(scene, B, hidden_lines=True)
    assert calls == [(True, True)]
    pipeline.compose(scene, B, hidden_lines=False)
    assert len(calls) == 1


@pytest.mark.parametrize("name", ["example_basic", "example_curved_demo", "random_seed3_3objects"])
def test_byte_identity_gate_on_another_numpy_build(name, monkeypatch):
    """The other-build branch of the byte-identity gate (§7.5 tolerances + SVG structure, no hash) passes,
    and the writer gives a v2 document (no ``receivers`` block) its v2 sub-group ids."""
    monkeypatch.setitem(GOLDEN, "build", "Python 0.0, numpy 0.0.0")
    test_switch_off_svg_and_stripped_json_are_byte_identical_to_v2(name)


@pytest.mark.parametrize("label, make", [("wall_and_ground", wall_and_ground_scene),
                                         ("fold_curved_cylinder", fold_curved_cylinder_scene),
                                         ("curved_on_wall", curved_on_wall_scene)])
def test_labels_follow_the_single_is_labelled_rule(label, make):
    """``_layer_labels`` (with its substring prefilter) writes exactly the names ``svg._is_labelled`` accepts
    (contract §5.1.7): one labelling rule."""
    import collections
    import re
    from castplane.output.svg import _is_labelled
    result = render(make())
    svg = result["svg"]
    layer = svg[svg.index('<g id="labels"'):]
    written = collections.Counter(re.findall(r'<text [^>]*?(?<!bold")>([^<]*)</text>', layer))
    expected = collections.Counter()
    for name, p in result["geometry"]["points"].items():
        oid, _dot, rest = name.partition(".")
        if p["image"] is None or not rest:
            continue
        if oid in ("L", "F"):
            expected[name] += 1
        elif _is_labelled(name.split(".")):
            expected[rest] += 1
    assert written == expected, label


def _concave_prism_scene(plate_bounds, position, polygon, lamp) -> dict:
    scene = wall_and_ground_scene()
    scene["objects"] = [{"id": "u", "type": "prism", "height": 1.0, "polygon": polygon,
                         "transform": {"position": position}}]
    scene["lights"] = [{"id": "lamp", "type": "point", "position": lamp}]
    scene["receivers"] = [{"id": "plate", "type": "plane", "normal": [0, 0, 1], "offset": 0, "bounds": plate_bounds}]
    scene["camera"] = {"position": [0, 4, 4], "target": [0, -3, 0], "focal_length_mm": 35, "frame_mm": [36, 24]}
    return scene


def test_concave_prism_on_plate_geometries_against_the_raycast():
    """§5.1.11 ``concave_prism_on_plate`` (review): with the plate beyond the closed arm of the U the expected
    region is the whole plate (the contract literal; the ray cast agrees); with a plate under the prism the
    notch floor and the wedge through the opening are lit, so the expected region is the plate minus them
    (area 36 - 2 - 2.625 = 31.375), not the whole plate. Both agree with the ray cast at IoU >= 0.99."""
    u_small = [[-1, -1], [1, -1], [1, 1], [0.5, 1], [0.5, -0.5], [-0.5, -0.5], [-0.5, 1], [-1, 1]]
    beyond = _concave_prism_scene([[-3, -4.5, 0], [3, -4.5, 0], [3, -2, 0], [-3, -2, 0]], [0, 0, 0], u_small,
                                  [0, 0.2, 0.7])
    u_big = [[-1.5, -1.5], [1.5, -1.5], [1.5, 1.5], [0.5, 1.5], [0.5, -0.5], [-0.5, -0.5], [-0.5, 1.5], [-1.5, 1.5]]
    under = _concave_prism_scene([[-3, 1, 0], [3, 1, 0], [3, 7, 0], [-3, 7, 0]], [0, 4, 0], u_big, [0, 4.5, 0.5])
    for label, scene, area in (("beyond the arm", beyond, 15.0), ("under the prism", under, 31.375)):
        validated = castplane.load_scene(scene)
        doc = castplane.render(validated)["geometry"]
        sh = shadow_of(doc, "plate", "u")
        got = sum(0.5 * abs(_shoelace(np.array([world(doc, n)[:2] for n in loop]))) for loop in sh["loops"])
        assert abs(got - area) <= 1e-9, (label, got)
        mask_doc, mask_ref = plate_masks(validated, doc, "plate")
        assert raster.iou(mask_doc, mask_ref) >= 0.99, (label, raster.iou(mask_doc, mask_ref))


def test_stages_cli_writes_a_once_and_receiver_frames_as_lists(tmp_path):
    """``castplane stages`` (contract §5.1.7): B is written without its ``A`` (``B["A"]`` is stage A itself),
    ``A["receivers"]`` frames and bounds functionals are serialised as lists."""
    from castplane.cli import EXIT_OK, main
    scene_path = tmp_path / "wall.json"
    scene_path.write_text(json.dumps(wall_and_ground_scene()), encoding="utf-8")
    out = tmp_path / "stages.json"
    assert main(["stages", str(scene_path), "-o", str(out), "--quiet"]) == EXIT_OK
    data = json.loads(out.read_text(encoding="utf-8"))
    assert "A" not in data["B"]
    ground, wall = data["A"]["receivers"]
    assert ground["frame"] is None and ground["psi"] is None
    assert isinstance(wall["frame"], list) and len(wall["frame"]) == 2
    assert all(isinstance(e, list) and len(e) == 3 for e in wall["frame"])
    assert isinstance(wall["psi"], list) and len(wall["psi"]) == 4 and all(len(row) == 4 for row in wall["psi"])


# --- review fix m4-hidden#0: the construction layer follows receivers[] order, not per_receiver key order ----

@pytest.mark.parametrize("hidden", [False, True])
@pytest.mark.parametrize("n_lights", [1, 2])
def test_construction_layer_is_independent_of_per_receiver_key_order(hidden, n_lights):
    """``write_svg`` of the canonical JSON round trip (``sort_keys``) equals ``write_svg`` of the in-memory
    document for two bounded receivers whose ids are not in code-point order (``wall`` then ``panel``):
    the F′_r markers and rays are emitted in ``receivers[]`` order (§5.0.6)."""
    import copy

    from castplane.output.geometry_json import dumps
    from castplane.output.svg import write_svg
    from tests.test_hidden import zbuffer_random_scene

    scene = zbuffer_random_scene(2)
    assert [r["id"] for r in scene["receivers"]][1:] == ["wall", "panel"]
    if n_lights == 2:
        extra = copy.deepcopy(scene["lights"][0])
        extra["id"] = "zz_second"
        if "position" in extra:
            extra["position"] = [p + d for p, d in zip(extra["position"], (0.9, -0.6, 0.4))]
        scene["lights"].append(extra)
    doc = castplane.render(castplane.load_scene(scene), hidden_lines=hidden)["geometry"]
    direct = write_svg(doc)
    assert "F′wall" in direct and "F′panel" in direct
    assert direct.index("F′wall") < direct.index("F′panel")
    assert write_svg(json.loads(dumps(doc))) == direct
