"""M4 bounded receivers, folds and per-receiver construction (contract §5.1.1–§5.1.5, §5.1.11; spec §9 / §10 M4).

The byte-identity gate of contract §5.1.2 / §5.1.8 / §5.1.11: with the new features switched off, the SVG of
every v2 conformance scene equals the v2 writer's output (``tests/golden/v2_svg_sha256.json``, generated by the
v2 code before M4) and the geometry JSON with the M4 keys stripped (``tools/regen_conformance.py
--strip-new-keys``) equals the committed v2 expected file.
"""

from __future__ import annotations

import hashlib
import json
import pathlib

import pytest

import castplane

ROOT = pathlib.Path(__file__).resolve().parents[1]
CASES = ROOT / "tests" / "conformance" / "cases"
GOLDEN = json.loads((ROOT / "tests" / "golden" / "v2_svg_sha256.json").read_text(encoding="utf-8"))


def v2_case_names() -> list[str]:
    return sorted(GOLDEN["sha256"])


def test_golden_hashes_cover_the_34_v2_cases():
    assert len(GOLDEN["sha256"]) == 34
    assert set(GOLDEN["sha256"]) <= {p.stem for p in CASES.glob("*.json")}


@pytest.mark.parametrize("name", v2_case_names())
def test_switch_off_svg_is_byte_identical_to_v2(name):
    scene = castplane.load_scene(CASES / f"{name}.json")
    svg = castplane.render(scene)["svg"]
    assert hashlib.sha256(svg.encode("utf-8")).hexdigest() == GOLDEN["sha256"][name]
